import express from 'express';
import cors from 'cors';
import Hello from './Hello.js';
import Lab5 from "./Lab5.js";
import CourseRoutes from "./kanbas/courses/routes.js";
import ModuleRoutes from './kanbas/modules/routes.js';
const app = express();
app.use(cors());
app.use(express.json());
Hello(app);
CourseRoutes(app);
ModuleRoutes(app);
Lab5(app);
app.listen(process.env.PORT || 4000);